CREATE SCHEMA "public";
CREATE TABLE "boss" (
	"boss_name" varchar PRIMARY KEY,
	"game_id" varchar NOT NULL,
	"metadata" json
);
CREATE TABLE "boss_summary" (
	"game_id" varchar NOT NULL,
	"run_id" varchar NOT NULL,
	"boss_seq" integer NOT NULL,
	"stage_index" integer,
	"stage_id" varchar,
	"boss_name" varchar NOT NULL,
	"entered_at" timestamp NOT NULL,
	"defeated_at" timestamp,
	"duration_ms" integer,
	"defeated" boolean,
	"damage_taken_in_boss" integer,
	"updated_at" timestamp NOT NULL
);
CREATE TABLE "choice_fact" (
	"choice_fact_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "choice_fact_choice_fact_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"game_id" varchar NOT NULL,
	"run_id" varchar NOT NULL,
	"occurred_at" timestamp NOT NULL,
	"stage_index" integer,
	"stage_id" varchar,
	"room_index" integer,
	"choice_context" varchar,
	"selected_upgrade_id" varchar NOT NULL,
	"options_present" json,
	"updated_at" timestamp NOT NULL,
	"event_id" integer NOT NULL
);
CREATE TABLE "death_fact" (
	"death_fact_id" varchar PRIMARY KEY,
	"game_id" varchar NOT NULL,
	"run_id" varchar NOT NULL,
	"occurred_at" timestamp NOT NULL,
	"stage_index" integer,
	"stage_id" varchar,
	"room_index" integer,
	"hp" integer,
	"max_hp" integer,
	"upgrades_snapshot" json,
	"updated_at" timestamp NOT NULL
);
CREATE TABLE "developer" (
	"developer_id" varchar PRIMARY KEY,
	"email" varchar NOT NULL CONSTRAINT "developer_email_key" UNIQUE,
	"display_name" varchar,
	"created_at" timestamp NOT NULL,
	"status" varchar NOT NULL,
	"auth_ref" varchar,
	"metadata" json
);
CREATE TABLE "developer_game" (
	"developer_id" varchar,
	"game_id" varchar,
	"role" varchar NOT NULL,
	"granted_at" timestamp NOT NULL,
	CONSTRAINT "developer_game_pkey" PRIMARY KEY("developer_id","game_id")
);
CREATE TABLE "event" (
	"event_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"game_id" varchar NOT NULL,
	"run_id" varchar NOT NULL,
	"occurred_at" timestamp NOT NULL,
	"ingested_at" timestamp NOT NULL,
	"event_type_id" bigint NOT NULL,
	"source_capture_id" varchar,
	"confidence" double precision,
	"pipeline_version" varchar,
	"model_version" varchar,
	"details" json NOT NULL
);
CREATE TABLE "event_type" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "event_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text
);
CREATE TABLE "game" (
	"game_id" varchar PRIMARY KEY,
	"name" varchar NOT NULL,
	"created_at" timestamp NOT NULL,
	"plugin_metadata" json,
	"game_metadata" json
);
CREATE TABLE "pipeline_job" (
	"job_id" varchar PRIMARY KEY,
	"game_id" varchar NOT NULL,
	"capture_id" varchar NOT NULL,
	"run_id" varchar,
	"status" varchar NOT NULL,
	"attempts" integer NOT NULL,
	"locked_by" varchar,
	"locked_at" timestamp,
	"pipeline_version" varchar,
	"model_version" varchar
);
CREATE TABLE "raw_capture" (
	"capture_id" varchar PRIMARY KEY,
	"game_id" varchar NOT NULL,
	"session_id" varchar NOT NULL,
	"run_id" varchar,
	"captured_at" timestamp NOT NULL,
	"received_at" timestamp NOT NULL,
	"input_device" varchar,
	"input_code" varchar,
	"mouse_x" integer,
	"mouse_y" integer,
	"screenshot_ref" varchar,
	"screenshot_hash" varchar,
	"image_width" integer,
	"image_height" integer,
	"status" varchar,
	"process_attempts" integer,
	"last_error" varchar,
	"game_version" varchar,
	"extra" json,
	"image_data" bytea
);
CREATE TABLE "room_summary" (
	"game_id" varchar NOT NULL,
	"run_id" varchar NOT NULL,
	"room_seq" integer NOT NULL,
	"stage_index" integer,
	"stage_id" varchar,
	"room_index" integer,
	"room_name_norm" varchar,
	"entered_at" timestamp NOT NULL,
	"exited_at" timestamp,
	"completion_ms" integer,
	"damage_taken_in_room" integer,
	"updated_at" timestamp NOT NULL
);
CREATE TABLE "run" (
	"run_id" varchar PRIMARY KEY,
	"game_id" varchar NOT NULL,
	"session_id" varchar NOT NULL,
	"started_at" timestamp NOT NULL,
	"ended_at" timestamp,
	"end_reason" varchar,
	"game_version" text,
	"run_meta" json
);
CREATE TABLE "run_summary" (
	"game_id" varchar NOT NULL,
	"run_id" varchar NOT NULL,
	"started_at" timestamp NOT NULL,
	"ended_at" timestamp,
	"duration_ms" integer,
	"result" varchar NOT NULL,
	"final_stage_id" varchar,
	"final_stage_index" integer,
	"final_room_index" integer,
	"total_damage_taken" integer,
	"choice_count" integer,
	"updated_at" timestamp NOT NULL
);
CREATE TABLE "session" (
	"session_id" varchar PRIMARY KEY,
	"game_id" varchar NOT NULL,
	"started_at" timestamp NOT NULL,
	"ended_at" timestamp,
	"client_info" json
);
CREATE TABLE "stage" (
	"stage_id" varchar PRIMARY KEY,
	"game_id" varchar NOT NULL,
	"stage_index" integer,
	"name_norm" varchar NOT NULL,
	"canonical_name" varchar,
	"first_seen_at" timestamp NOT NULL,
	"last_seen_at" timestamp NOT NULL,
	"metadata" json
);
CREATE UNIQUE INDEX "boss_pkey" ON "boss" ("boss_name");
CREATE INDEX "boss_summary_game_id_boss_id_idx" ON "boss_summary" ("game_id","boss_name");
CREATE INDEX "boss_summary_game_id_run_id_idx" ON "boss_summary" ("game_id","run_id");
CREATE INDEX "boss_summary_stage_id_idx" ON "boss_summary" ("stage_id");
CREATE INDEX "choice_fact_game_id_selected_upgrade_id_idx" ON "choice_fact" ("game_id","selected_upgrade_id");
CREATE UNIQUE INDEX "choice_fact_pkey" ON "choice_fact" ("choice_fact_id");
CREATE INDEX "choice_fact_run_id_occurred_at_idx" ON "choice_fact" ("run_id","occurred_at");
CREATE INDEX "choice_fact_stage_id_idx" ON "choice_fact" ("stage_id");
CREATE INDEX "death_fact_game_id_occurred_at_idx" ON "death_fact" ("game_id","occurred_at");
CREATE UNIQUE INDEX "death_fact_pkey" ON "death_fact" ("death_fact_id");
CREATE INDEX "death_fact_run_id_occurred_at_idx" ON "death_fact" ("run_id","occurred_at");
CREATE INDEX "death_fact_stage_id_idx" ON "death_fact" ("stage_id");
CREATE UNIQUE INDEX "developer_email_key" ON "developer" ("email");
CREATE UNIQUE INDEX "developer_pkey" ON "developer" ("developer_id");
CREATE INDEX "developer_game_game_id_idx" ON "developer_game" ("game_id");
CREATE UNIQUE INDEX "developer_game_pkey" ON "developer_game" ("developer_id","game_id");
CREATE INDEX "event_event_type_id_occurred_at_idx" ON "event" ("event_type_id","occurred_at");
CREATE INDEX "event_game_id_occurred_at_idx" ON "event" ("game_id","occurred_at");
CREATE UNIQUE INDEX "event_pkey" ON "event" ("event_id");
CREATE INDEX "event_run_id_occurred_at_idx" ON "event" ("run_id","occurred_at");
CREATE UNIQUE INDEX "event_type_pkey" ON "event_type" ("id");
CREATE UNIQUE INDEX "game_pkey" ON "game" ("game_id");
CREATE UNIQUE INDEX "pipeline_job_capture_id_idx" ON "pipeline_job" ("capture_id");
CREATE INDEX "pipeline_job_game_id_idx" ON "pipeline_job" ("game_id");
CREATE UNIQUE INDEX "pipeline_job_pkey" ON "pipeline_job" ("job_id");
CREATE INDEX "pipeline_job_run_id_idx" ON "pipeline_job" ("run_id");
CREATE INDEX "pipeline_job_status_idx" ON "pipeline_job" ("status");
CREATE INDEX "raw_capture_game_id_session_id_captured_at_idx" ON "raw_capture" ("game_id","session_id","captured_at");
CREATE UNIQUE INDEX "raw_capture_pkey" ON "raw_capture" ("capture_id");
CREATE INDEX "raw_capture_run_id_captured_at_idx" ON "raw_capture" ("run_id","captured_at");
CREATE INDEX "raw_capture_status_received_at_idx" ON "raw_capture" ("status","received_at");
CREATE INDEX "room_summary_game_id_run_id_idx" ON "room_summary" ("game_id","run_id");
CREATE INDEX "room_summary_game_id_stage_index_idx" ON "room_summary" ("game_id","stage_index");
CREATE INDEX "room_summary_stage_id_idx" ON "room_summary" ("stage_id");
CREATE INDEX "run_game_id_started_at_idx" ON "run" ("game_id","started_at");
CREATE UNIQUE INDEX "run_pkey" ON "run" ("run_id");
CREATE INDEX "run_session_id_started_at_idx" ON "run" ("session_id","started_at");
CREATE INDEX "run_summary_game_id_started_at_idx" ON "run_summary" ("game_id","started_at");
CREATE INDEX "session_game_id_started_at_idx" ON "session" ("game_id","started_at");
CREATE UNIQUE INDEX "session_pkey" ON "session" ("session_id");
CREATE UNIQUE INDEX "stage_game_id_name_norm_idx" ON "stage" ("game_id","name_norm");
CREATE INDEX "stage_game_id_stage_index_idx" ON "stage" ("game_id","stage_index");
CREATE UNIQUE INDEX "stage_pkey" ON "stage" ("stage_id");
ALTER TABLE "boss" ADD CONSTRAINT "boss_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "game"("game_id");
ALTER TABLE "boss_summary" ADD CONSTRAINT "boss_summary_boss_id_fkey" FOREIGN KEY ("boss_name") REFERENCES "boss"("boss_name");
ALTER TABLE "boss_summary" ADD CONSTRAINT "boss_summary_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "game"("game_id");
ALTER TABLE "boss_summary" ADD CONSTRAINT "boss_summary_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "run"("run_id");
ALTER TABLE "boss_summary" ADD CONSTRAINT "boss_summary_stage_id_fkey" FOREIGN KEY ("stage_id") REFERENCES "stage"("stage_id");
ALTER TABLE "choice_fact" ADD CONSTRAINT "choice_fact_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "event"("event_id");
ALTER TABLE "choice_fact" ADD CONSTRAINT "choice_fact_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "game"("game_id");
ALTER TABLE "choice_fact" ADD CONSTRAINT "choice_fact_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "run"("run_id");
ALTER TABLE "choice_fact" ADD CONSTRAINT "choice_fact_stage_id_fkey" FOREIGN KEY ("stage_id") REFERENCES "stage"("stage_id");
ALTER TABLE "death_fact" ADD CONSTRAINT "death_fact_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "game"("game_id");
ALTER TABLE "death_fact" ADD CONSTRAINT "death_fact_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "run"("run_id");
ALTER TABLE "death_fact" ADD CONSTRAINT "death_fact_stage_id_fkey" FOREIGN KEY ("stage_id") REFERENCES "stage"("stage_id");
ALTER TABLE "developer_game" ADD CONSTRAINT "developer_game_developer_id_fkey" FOREIGN KEY ("developer_id") REFERENCES "developer"("developer_id");
ALTER TABLE "developer_game" ADD CONSTRAINT "developer_game_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "game"("game_id");
ALTER TABLE "event" ADD CONSTRAINT "event_event_type_id_fkey" FOREIGN KEY ("event_type_id") REFERENCES "event_type"("id");
ALTER TABLE "event" ADD CONSTRAINT "event_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "game"("game_id");
ALTER TABLE "event" ADD CONSTRAINT "event_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "run"("run_id");
ALTER TABLE "event" ADD CONSTRAINT "event_source_capture_id_fkey" FOREIGN KEY ("source_capture_id") REFERENCES "raw_capture"("capture_id");
ALTER TABLE "pipeline_job" ADD CONSTRAINT "pipeline_job_capture_id_fkey" FOREIGN KEY ("capture_id") REFERENCES "raw_capture"("capture_id");
ALTER TABLE "pipeline_job" ADD CONSTRAINT "pipeline_job_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "game"("game_id");
ALTER TABLE "pipeline_job" ADD CONSTRAINT "pipeline_job_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "run"("run_id");
ALTER TABLE "raw_capture" ADD CONSTRAINT "raw_capture_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "game"("game_id");
ALTER TABLE "raw_capture" ADD CONSTRAINT "raw_capture_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "run"("run_id");
ALTER TABLE "raw_capture" ADD CONSTRAINT "raw_capture_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "session"("session_id");
ALTER TABLE "room_summary" ADD CONSTRAINT "room_summary_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "game"("game_id");
ALTER TABLE "room_summary" ADD CONSTRAINT "room_summary_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "run"("run_id");
ALTER TABLE "room_summary" ADD CONSTRAINT "room_summary_stage_id_fkey" FOREIGN KEY ("stage_id") REFERENCES "stage"("stage_id");
ALTER TABLE "run" ADD CONSTRAINT "run_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "game"("game_id");
ALTER TABLE "run" ADD CONSTRAINT "run_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "session"("session_id");
ALTER TABLE "run_summary" ADD CONSTRAINT "run_summary_final_stage_id_fkey" FOREIGN KEY ("final_stage_id") REFERENCES "stage"("stage_id");
ALTER TABLE "run_summary" ADD CONSTRAINT "run_summary_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "game"("game_id");
ALTER TABLE "run_summary" ADD CONSTRAINT "run_summary_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "run"("run_id");
ALTER TABLE "session" ADD CONSTRAINT "session_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "game"("game_id");
ALTER TABLE "stage" ADD CONSTRAINT "stage_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "game"("game_id");
